### ISSUE TITLE
Please add license

### ISSUE THREAD

**Issue by ohanhi** [craigp/elixir_xoauth2#3]
This looks like something we could use in our project, but without a proper OSS license it would violate your rights. Can you add a LICENSE file to the repository so we can keep working on this library?

**Comment by craigp** [comment]
Hey there ~ happy to, added one now. However, it's worth pointing out that this was a learning exercise for me and I never really finished or documented it at all. You might want to check out https://github.com/parroty/oauth2ex which is far more complete.

**Comment by ohanhi** [comment]
Nice, thank you! :+1:
